name: Test Karate
on:
  push:
    branches:
      - main

jobs:
  karate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          
      - name: Run Karate tests
        run: |
          ./gradlew test
